#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "fractal.h"
#include "image.h"
/*
	generate and save the entire fractal
	returns:	0 if successful
				1 otherwise
*/
int generate_fractal(char *file, float width, float height, int workers) {
	/*	TODO: use fork(), mmap(), and munmap() to create a region of shared memory
			to store fractal data, as generated by several child processes	*/
        color_t *fractal_data = mmap(NULL,sizeof(color_t)*width*height,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANONYMOUS,0,0);
        // mmap creates another big heap, malloc works on an existing heap
        pid_t childpid[workers];
        for (int i=0; i<workers; i++) {
            childpid[i] = fork();
            if (childpid[i] == 0) {
                generate_fractal_region(fractal_data, width, height, i*height/workers, height/workers);
                munmap(NULL,sizeof(color_t)*width*height);
                exit(0);
            }
        }
        int status;
        for (int i=0; i<workers; i++) {
            waitpid(childpid[i],&status,0);
        }
        /*
		save the generated fractal data into the file specified by argv[1]
	*/
	if (save_image_data(file, fractal_data, width, height)) {
		fprintf(stderr, "error saving to image file.\n");
		return 1;
	}
        munmap(NULL,sizeof(color_t)*width*height);
        printf("Complete.\n");
        return 0;
}
